In [198]:
import numpy as np

# Generate 2 matrices (x1 fake, x2 real)
x1 = np.random.randint(-10, 10, size=(1000,800))
x2 = np.random.randint(-10, 10, size=(1000,800))


# means of data
m1 = x1.mean(axis=0)
m2 = x2.mean(axis=0)

# force fake data to have 0 mean
x1 = x1 - m1



# Covariance matrixes
sigma1 = np.cov(x1.T)
sigma2 = np.cov(x2.T)

sigma1_sqr = np.zeros_like(sigma1)
sigma2_sqr = np.zeros_like(sigma2)


u1,s1,v1 = np.linalg.svd(sigma1)
u2,s2,v2 = np.linalg.svd(sigma2)


threshold = 10e-14

# Zero the eigenvalues that are less than the threshold
non_zero_inde = (s1>threshold).nonzero()
sd1 = np.zeros_like(s1)
sd1[non_zero_inde] = s1[non_zero_inde]**(-.5)

z1 = np.dot(u1, np.dot(np.diag(sd1), np.dot(v1, x1.T))).T

#Now our data has covariance of sigma2
x1_tilde = np.dot(u2, np.dot(np.diag(np.sqrt(s2)),np.dot(np.diag(sd1), np.dot(v1, x1.T)))).T


# Add the mean of X2
x1_star = x1_tilde + m2

In [194]:
np.cov(x1_tilde.T)

array([[ 34.40398799,   0.82852452,   0.79786987, ...,  -1.26416817,
          1.17447848,   0.93257257],
       [  0.82852452,  32.39652052,   1.21788589, ...,   0.90838238,
         -0.51488889,   0.20336336],
       [  0.79786987,   1.21788589,  33.11038639, ...,  -0.90728929,
          0.20628829,   0.58670671],
       ..., 
       [ -1.26416817,   0.90838238,  -0.90728929, ...,  33.12132032,
         -1.87722623,   1.28344344],
       [  1.17447848,  -0.51488889,   0.20628829, ...,  -1.87722623,
         31.81181081,  -0.95511512],
       [  0.93257257,   0.20336336,   0.58670671, ...,   1.28344344,
         -0.95511512,  32.84724725]])

In [195]:
sigma2

array([[ 34.40398799,   0.82852452,   0.79786987, ...,  -1.26416817,
          1.17447848,   0.93257257],
       [  0.82852452,  32.39652052,   1.21788589, ...,   0.90838238,
         -0.51488889,   0.20336336],
       [  0.79786987,   1.21788589,  33.11038639, ...,  -0.90728929,
          0.20628829,   0.58670671],
       ..., 
       [ -1.26416817,   0.90838238,  -0.90728929, ...,  33.12132032,
         -1.87722623,   1.28344344],
       [  1.17447848,  -0.51488889,   0.20628829, ...,  -1.87722623,
         31.81181081,  -0.95511512],
       [  0.93257257,   0.20336336,   0.58670671, ...,   1.28344344,
         -0.95511512,  32.84724725]])

In [196]:
x2.std(), x_star.std()

(5.7656562245223606, 5.717516943569124)

In [197]:
x2.mean(axis=0), x1_star.mean(axis=0)

(array([-0.696, -0.874, -0.418, -0.705, -0.717, -0.65 , -0.627, -0.477,
        -0.299, -0.628, -0.538, -0.875, -0.491, -0.667, -0.792, -0.541,
        -0.189, -0.474, -0.311, -0.22 , -0.882, -0.273, -0.304, -0.376,
        -0.257, -0.562, -0.363, -0.742, -0.743, -0.635, -0.846, -0.599,
        -0.478, -0.476, -0.276, -0.267, -0.747, -0.699, -0.584, -0.525,
        -0.254, -0.449, -0.58 , -0.404, -0.649, -0.517, -0.467, -0.621,
        -0.822, -0.507, -0.564, -0.489, -0.402, -0.592, -0.737, -0.534,
        -0.402, -0.793, -0.58 , -0.12 , -0.586, -0.581, -0.461, -0.734,
        -0.225, -0.655, -0.785, -0.389, -0.298, -0.298, -0.518, -0.383,
        -0.51 , -0.323, -0.44 , -0.238, -0.441, -0.558, -0.781, -0.645,
        -0.281, -0.466, -0.689, -0.31 , -0.62 , -0.611, -0.583, -0.578,
        -0.552, -0.429, -0.586, -0.399, -0.222, -0.326, -0.548, -0.145,
        -0.209, -0.807, -0.23 , -0.814, -0.832, -0.431, -0.456, -0.631,
        -0.462, -0.653, -0.379, -0.472, -0.696, -0.122, -0.501, 